server:
    port: 9098
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:9098/eureka
spring:
    application:
        name: Donor
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/donor?serverTimezone=UTC
        username: "root"
        password: 
        nitialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
